name: Cordova

on: push

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: cordova-plugin-genius-scan-demo
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v1
    - run: npm install -g cordova
    - run: npm install
    - run: cordova prepare
    - run: cordova build
